### ISSUE TITLE
Write Unittests for controller.py

### ISSUE THREAD

**Issue by Michaluch** [Social-projects-Rivne/SMS_admin_autotesting#1]

**Comment by alexbass16** [comment]
assertEqual for get_index, get_error404, get_login

**Comment by borisalexj** [comment]
Had written tests for "subject CRUD" in admin_controller.

**Comment by borisalexj** [comment]
Completed writing tests for School/Subject CRUD in controller.py
Negative tests included.
Coverage 94%

**Comment by borisalexj** [comment]
improved negative tests for School and Subject CRUD.

**Comment by borisalexj** [comment]
Finished. Coverage 100%.
